// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi_IkgSlB3hm1B58-Na9iqW9q7AndOSxA',
    appId: '1:522432310223:web:3020e7389af69c33f2c0ba',
    messagingSenderId: '522432310223',
    projectId: 'cascar-89520',
    authDomain: 'cascar-89520.firebaseapp.com',
    storageBucket: 'cascar-89520.firebasestorage.app',
    measurementId: 'G-B74RXNYN7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiyoEfvlZ13HXMMEmFT5GAZcu9XuF1Owk',
    appId: '1:522432310223:android:403411618a348093f2c0ba',
    messagingSenderId: '522432310223',
    projectId: 'cascar-89520',
    storageBucket: 'cascar-89520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvSYCFuaskgwHFmSgvqRtti1kiq3-E30',
    appId: '1:522432310223:ios:9d6039d6bb1ab3c5f2c0ba',
    messagingSenderId: '522432310223',
    projectId: 'cascar-89520',
    storageBucket: 'cascar-89520.firebasestorage.app',
    iosBundleId: 'com.example.casacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvSYCFuaskgwHFmSgvqRtti1kiq3-E30',
    appId: '1:522432310223:ios:9d6039d6bb1ab3c5f2c0ba',
    messagingSenderId: '522432310223',
    projectId: 'cascar-89520',
    storageBucket: 'cascar-89520.firebasestorage.app',
    iosBundleId: 'com.example.casacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi_IkgSlB3hm1B58-Na9iqW9q7AndOSxA',
    appId: '1:522432310223:web:7182a13b571806c9f2c0ba',
    messagingSenderId: '522432310223',
    projectId: 'cascar-89520',
    authDomain: 'cascar-89520.firebaseapp.com',
    storageBucket: 'cascar-89520.firebasestorage.app',
    measurementId: 'G-Q3Z81XH1ML',
  );

}